apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: sample-app
  path: patch-deployment.yaml